name: extract-distfeeds

on:
  schedule:
    # Run at minute 45 of every 6th hour (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '45 */6 * * *'
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:  
  extract:
    runs-on: ubuntu-24.04
    steps:
      - name: Install binwalk
        run: |
          sudo apt update
          sudo apt install -y binwalk
      - name: Download and extract
        run: |
          curl https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/openwrt-mediatek-filogic-zbtlink_zbt-z8103ax-c-squashfs-sysupgrade.bin --output sysupgrade.bin
          binwalk -e sysupgrade.bin
          binwalk -e _sysupgrade.bin.extracted/sysupgrade-zbtlink_zbt-z8103ax-c/root
      - name: Prepare artifact
        run: |
          mkdir artifact
          cp _sysupgrade.bin.extracted/sysupgrade-zbtlink_zbt-z8103ax-c/_root.extracted/squashfs-root/etc/apk/repositories.d/distfeeds.list .
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: distfeeds.list
          archive: false
